CREATE TABLE tbl_user (
    id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL UNIQUE,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) UNIQUE,
    status TINYINT(1) DEFAULT 1,
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedDate DATETIME
);

CREATE TABLE tbl_role (
    id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    roleName VARCHAR(50) NOT NULL UNIQUE,
    roleDescription VARCHAR(255),
    status TINYINT(1) DEFAULT 1,
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedDate DATETIME
);

